site_name: ClickHouse SQL Reference Sheet # Name of the documentation site
site_url: https://maruthiprithivi.github.io/click_reference_sheet/ # Update with your GitHub username
repo_url: https://github.com/maruthiprithivi/click_reference_sheet # Update with your GitHub username
repo_name: click_reference_sheet
edit_uri: edit/main/docs/
site_description: A comprehensive SQL command reference sheet for ClickHouse Cloud Field Team # Site description

theme:
  name: material
  language: en
  icon:
    logo: material/database # Adding database icon
    repo: fontawesome/brands/github # GitHub repository icon
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate # Enable code annotation
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      htmlmin_opts:
        remove_comments: true # Remove HTML comments during minification

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __code
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - def_list
  - mdx_truly_sane_lists
  - pymdownx.tasklist:
      custom_checkbox: true # Enable custom checkboxes

nav:
  - Home: index.md
  - Basic Operations:
      - Connection: basic-operations/connection.md
      - Databases: basic-operations/databases.md
      - Tables: basic-operations/tables.md
  - Data Operations:
      - Inserting Data: data-operations/insert.md
      - Querying Data: data-operations/select.md
      - Updating Data: data-operations/update.md
  - System Commands:
      - Monitoring: system-commands/monitoring.md
      - Performance: system-commands/performance.md
  - Advanced Operations:
      - Maintenance: advanced-operations/maintenance.md
      - Optimization: advanced-operations/optimization.md
      - Security: advanced-operations/security.md
