name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main # Set a branch to deploy
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write # Allows pushing to the repository

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Set up Python # Ensure Python is set up
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: "pip" # Cache pip dependencies

      - name: Install dependencies # Install project dependencies
        run: |
          pip install -r requirements.txt
          pip install mkdocs-material

      - name: Deploy to GitHub Pages # Deploy documentation
        run: mkdocs gh-deploy --force
